// This assembly is included in the following assemblies:
//
//assembly-br-configuring-operator-based-deployments.adoc

[id='assembly-br-configuring-resource-limits-and-requests-operator_{context}']
= Configuring resource limits and requests for Operator-based broker deployments

When you create an Operator-based broker deployment, the broker Pods in the deployment run in a Stateful Set on a node in your OpenShift cluster. You can configure the Custom Resource (CR) instance for the deployment to specify the host-node compute resources used by the broker container that runs in each Pod. By specifying limit and request values for CPU and memory (RAM), you can ensure satisfactory performance of the broker Pods.

[IMPORTANT]
====
* To configure resource limits and requests for the brokers in an Operator-based deployment, you must be using __at least__ the latest version of the Operator for {BrokerName} 7.7 (that is, version 0.17). To learn how to upgrade the Operator to the latest version for {BrokerName} {BrokerVersion}, see xref:assembly_br-upgrading-operator-based-broker-deployments_{context}[].
* You must add configuration for limits and requests to the CR instance for your broker deployment *before* deploying the CR for the first time. You *cannot* add the configuration to a broker deployment that is already running.
* It is not possible for Red Hat to recommend values for limits and requests because these are based on your specific messaging system use-cases and the resulting architecture that you have implemented. However, it __is__ recommended that you test and tune these values in a development environment before configuring them for your production environment.
* If you have included an address settings configuration in the Custom Resource (CR) instance for your broker deployment, the Operator runs a type of container called an __Init Container__ (in addition to the broker container) when initializing each broker Pod. In this case, any resource limits and requests that you configure for each broker container also apply to each Init Container. For more information about the use of Init Containers in broker deployments, see xref:con-br-understanding-the-default-address-settings-configuration-operator_{context}[].
====

You can specify the following limit and request values:

`CPU limit`:: For each broker container running in a Pod, this value is the maximum amount of host-node CPU that the container can consume. If a broker container attempts to exceed the specified CPU limit, OpenShift throttles the container. This ensures that containers have consistent performance, regardless of the number of Pods running on a node.
`Memory limit`:: For each broker container running in a Pod, this value is the maximum amount of host-node memory that the container can consume. If a broker container attempts to exceed the specified memory limit, OpenShift terminates the container. The broker Pod restarts.
`CPU request`:: For each broker container running in a Pod, this value is the amount of host-node CPU that the container requests. The OpenShift scheduler considers the CPU request value during Pod placement, to bind the broker Pod to a node with sufficient compute resources.
+
The CPU request value is the __minimum__ amount of CPU that the broker container requires to run. However, if there is no contention for CPU on the node, the container can use all available CPU. If you have specified a CPU limit, the container cannot exceed that amount of CPU usage. If there is CPU contention on the node, CPU request values provide a way for OpenShift to weigh CPU usage across all containers.
`Memory request`:: For each broker container running in a Pod, this value is the amount of host-node memory that the container requests. The OpenShift scheduler considers the memory request value during Pod placement, to bind the broker Pod to a node with sufficient compute resources.
+
The memory request value is the __minimum__ amount of memory that the broker container requires to run. However, the container can consume as much available memory as possible. If you have specified a memory limit, the broker container cannot exceed that amount of memory usage.

CPU is measured in units called millicores. Each node in an OpenShift cluster inspects the operating system to determine the number of CPU cores on the node. Then, the node multiplies that value by 1000 to express the total capacity. For example, if a node has two cores, the CPU capacity of the node is expressed as `2000m`. Therefore, if you want to use one-tenth of a single core, you specify a value of `100m`.

Memory is measured in bytes. You can specify the value using byte notation (E, P, T, G, M, K) or the binary equivalents (Ei, Pi, Ti, Gi, Mi, Ki). The value that you specify must include a unit.

include::../../modules/broker-ocp/proc-br-configuring-broker-limits-and-requests-operator.adoc[leveloffset=+1]
