// Module included in the following assemblies:
//
// assembly-operator-lifecycle-manager.adoc

[id='proc-br-installing-operator-to-project-from-operatorhub_{context}']
= Deploying the Operator from OperatorHub

This procedure shows how to use OperatorHub to deploy the latest version of the Operator for {BrokerName} to a specified OpenShift project.

IMPORTANT: Deploying the Operator for {BrokerName} using the OperatorHub requires cluster administrator privileges.

.Prerequisites
* The `Red Hat Integration - {BrokerName}` Operator must be available in OperatorHub. If you do not see the Operator automatically available, see xref:proc_br-installing-broker-operator-in-operatorhub_{context}[] for instructions on manually installing the Operator in OperatorHub.

.Procedure
. Log in to the {OpenShiftContainerName} web console as a cluster administrator.
. In left navigation menu, click menu:Operators[OperatorHub].
. On the *Project* drop-down menu at the top of the *OperatorHub* page, select the project in which you want to deploy the Operator.
. On the *OperatorHub* page, use the *Filter by keyword...* box to find the `Red Hat Integration - {BrokerName}` Operator.
+
NOTE: In OperatorHub, you might find more than one Operator than includes `{BrokerName}` in its name. Ensure that you click the `Red Hat Integration - {BrokerName}` Operator. When you click this Operator, review the information pane that opens. For {BrokerName} {BrokerVersion}, the latest version tag of this Operator is `{latestOperatorTag}`.

. Click the `Red Hat Integration - {BrokerName}` Operator. On the dialog box that appears, click *Install*.
. On the *Install Operator* page:
.. Under *Update Channel*, ensure that the radio button entitled `current` is selected. This option specifies the channel used to track and receive updates for the Operator. The `current` value specifies that the {BrokerName} {BrokerVersion} channel is used.
.. Under *Installation Mode*, ensure that the radio button entitled *A specific namespace on the cluster* is selected.
.. From the *Installed Namespace* drop-down menu, select the project in which you want to install the Operator.
.. Under *Approval Strategy*, ensure that the radio button entitled `Automatic` is selected. This option specifies that updates to the Operator do not require manual approval for installation to take place.
.. Click *Install*.

When the Operator installation is complete, the *Installed Operators* page opens. You should see that the `Red Hat Integration - {BrokerName}` Operator is installed in the project namespace that you specified.

.Additional resources
* To learn how to create a broker deployment in a project that has the Operator for {BrokerName} installed, see xref:proc_br-deploying-basic-broker-operator_{context}[].
