// Module included in the following assemblies:
//
// assembly-operator-lifecycle-manager.adoc

[id='proc_br-installing-broker-operator-in-operatorhub_{context}']
= Installing the Operator in OperatorHub

In OperatorHub, the name of the Operator for {BrokerName} {BrokerVersion} is `Red Hat Integration - {BrokerName}`. You should see the Operator automatically available in OperatorHub. However, if you do not see it, follow this procedure to manually install the Operator in OperatorHub.

.Procedure

. In your web browser, navigate to the *Software Downloads* page for link:https://access.redhat.com/jbossnetwork/restricted/listSoftware.html?product=jboss.amq.broker&downloadType=distributions&version={BrokerVersionWithMicro}[{BrokerName} {BrokerVersionWithMicro} releases].

. Ensure that the value of the *Version* drop-down list is set to `{BrokerVersionWithMicro}` and the *Releases* tab is selected.

. Next to *{BrokerName} {BrokerVersion} Operator Installation Files*, click *Download*.
+
Download of the `amq-broker-operator-{BrokerVersionWithMicro}-ocp-install-examples.zip` compressed archive automatically begins.

. When the download has completed, move the archive to your chosen installation directory. The following example moves the archive to a directory called `~/broker/operator`.
+
[source,bash,options="nowrap",subs="+attributes"]
----
mkdir ~/broker/operator
mv amq-broker-operator-{BrokerVersionWithMicro}-ocp-install-examples.zip ~/broker/operator
----

. In your chosen installation directory, extract the contents of the archive. For example:
+
[source,bash,options="nowrap",subs="+attributes"]
----
cd ~/broker/operator
unzip amq-broker-operator-{BrokerVersionWithMicro}-ocp-install-examples.zip
----

. Switch to the directory for the Operator archive that you extracted. For example:
+
[source,bash,options="nowrap",subs="+attributes"]
----
cd amq-broker-operator-{BrokerVersionWithMicro}-ocp-install-examples
----

. Log in to {OpenShiftContainerName} as a cluster administrator. For example:
+
[source,bash,options="nowrap"]
----
$ oc login -u system:admin
----

. Install the Operator in OperatorHub.
+
[source,bash,options="nowrap"]
----
$ oc create -f deploy/catalog_resources/activemq-artemis-operatorsource.yaml
----
+
After a few minutes, the Operator for {BrokerName} {BrokerVersion} is available in the *OperatorHub* section of the {OpenShiftContainerName} web console. The name of the Operator is `Red Hat Integration - {BrokerName}`.
