// Module included in the following assemblies:
//
// assembly-deploying-broker-using-operator.adoc

[id='con-br-operator-deployment-notes_{context}']
= Operator deployment notes

This section describes some important considerations when planning an Operator-based deployment

* Deploying the Custom Resource Definitions (CRDs) that accompany the {BrokerName} Operator requires cluster administrator privileges for your {ClientTool}  cluster. When the Operator is deployed, non-administrator users can create broker instances via corresponding Custom Resources (CRs). To enable regular users to deploy CRs, the cluster administrator must first assign roles and permissions to the CRDs. For more information, see link:{clusterRoleLink}[Creating cluster roles for Custom Resource Definitions] in the {OpenShiftContainerName} documentation.

* When you update your cluster with the CRDs for the latest Operator version, this update affects *all* projects in the cluster. Any broker Pods deployed from previous versions of the Operator might become unable to update their status.
ifndef::UpstreamBuild[]
When you click the Logs tab of a running broker Pod in the {ClientTool}  Container Platform web console, you see messages indicating that 'UpdatePodStatus' has failed. However, the broker Pods and Operator in that project continue to work as expected.
endif::[]
To fix this issue for an affected project, you must also upgrade that project to use the latest version of the Operator.

* You cannot create more than one broker deployment in a given {ClientTool}  project by deploying multiple broker Custom Resource (CR) instances. However, when you have created a broker deployment in a project, you *can* deploy multiple CR instances for addresses.

* If you intend to deploy brokers with persistent storage and do not have container-native storage in your {ClientTool}  cluster, you need to manually provision Persistent Volumes (PVs) and ensure that these are available to be claimed by the Operator. For example, if you want to create a cluster of two brokers with persistent storage (that is, by setting `persistenceEnabled=true` in your CR), you need to have two persistent volumes available. By default, each broker instance requires storage of 2 GiB.
+
If you specify `persistenceEnabled=false` in your CR, the deployed brokers uses _ephemeral_ storage. Ephemeral storage means that that every time you restart the broker Pods, any existing data is lost.
+
For more information about provisioning persistent storage in {OpenShiftContainerName}, see:
+
ifndef::UpstreamBuild[]
** link:https://docs.openshift.com/container-platform/4.1/storage/understanding-persistent-storage.html[Understanding persistent storage] ({OpenShiftContainerName} 4.1 and later)
** link:https://docs.openshift.com/container-platform/3.11/architecture/additional_concepts/storage.html[Persistent Storage] ({OpenShiftContainerName} 3.11).
endif::[]
ifdef::UpstreamBuild[]
** link:https://kubernetes.io/docs/concepts/storage/persistent-volumes[Persistent Volumes]
endif::[]

ifndef::UpstreamBuild[]
* You must add configuration for the following items to the main broker CR instance *before* deploying the CR for the first time.
+
--
** xref:proc-br-configuring-broker-storage-size_{context}[The size of the Persistent Volume Claim (PVC) required by each broker in a deployment for persistent storage]
** xref:proc-br-configuring-broker-limits-and-requests_{context}[Limits and requests for memory and CPU for each broker in a deployment]

You *cannot* add configuration for the listed items to a broker deployment that is already running.
--
endif::[]
